architecture:
  _target_: llm_synthesis.transformers.synthesis_extraction.dspy_synthesis_extraction.DspyStructuredSynthesisExtractor
  signature:
    _target_: llm_synthesis.transformers.synthesis_extraction.dspy_synthesis_extraction.make_dspy_structured_synthesis_extractor_signature
    signature_name: "StructuredSynthesisSignature"
    instructions: "Extract the structured synthesis from the synthesis paragraph."
    input_description: "The synthesis paragraph to extract the structured synthesis from."
    output_name: "structured_synthesis"
    output_description: "The extracted structured synthesis."
  lm:
    _target_: llm_synthesis.utils.dspy_utils.get_llm_from_name
    llm_name: "gemini-2.0-flash"
    model_kwargs:
      temperature: 0.0
    system_prompt: "You are a helpful assistant that extracts the structured synthesis from the synthesis paragraph."