# PDF processing configuration
# Set these to enable PDF text extraction before synthesis processing
pdf_dir: "../test"  # Path to directory containing PDF files (e.g., "data/pdf_papers")
txt_dir: "../test"  # Path to save extracted text files (e.g., "data/txt_papers/docling")
extraction_process: "mistral"  # PDF extraction method: "docling" or "mistral"
