
repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.7.4
      hooks:
          # Run the linter with auto-fixing enabled
          - id: ruff
            args: ["--fix"]
          # Run the formatter with auto-fixing enabled
          - id: ruff-format