# Defaults
defaults:
  - _self_
  - data_loader: null
  - synthesis_extraction: null
  - paragraph_extraction: null
  - figure_extraction: null
  - judge: null
  - result_save: null

# Dir handling
hydra:
  job:
    chdir: true
  run:
    dir: results/single_run/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: results/multi_run/${now:%Y-%m-%d}/${now:%H-%M-%S}
