# Defaults
defaults:
  - _self_
  - data_loader: default
  - synthesis_extraction: default
  - paragraph_extraction: default
  - judge: default
  # Added `result_save` to the defaults list. This was missing and caused a
  # `ConfigAttributeError` because the script needs this configuration to know
  # how to save the results.
  - result_save: default

# Dir handling
hydra:
  job:
    chdir: true
  run:
    dir: results/single_run/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: results/multi_run/${now:%Y-%m-%d}/${now:%H-%M-%S}
