# lm:
#   name: "gemini-2.0-flash"
#   temperature: 0.0
# TODO: different LLM for paragraph extraction and synthesis extraction

architecture:
  _target_: llm_synthesis.transformers.text_extraction.dspy_extraction.DspyTextExtractor
  signature:
    _target_: llm_synthesis.transformers.text_extraction.dspy_extraction.make_dspy_text_extractor_signature
    signature_name: "TextToParagraphSignature"
    instructions: "Extract the synthesis paragraph from the publication text."
    input_description: "The publication text to extract the synthesis paragraph from."
    output_name: "synthesis_paragraph"
    output_description: "The extracted synthesis paragraph."
  lm:
    _target_: llm_synthesis.utils.dspy_utils.get_llm_from_name
    llm_name: "gemini-2.0-flash"
    model_kwargs:
      temperature: 0.0

  # system_prompt: wip
