# Defaults
defaults:
  - _self_
  - data: default
  - synthesis_extraction: default
  - paragraph_extraction: default

# Dir handling
hydra:
  job:
    chdir: true
  run:
    dir: results/single_run/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: results/multi_run/${now:%Y-%m-%d}/${now:%H-%M-%S}
