architecture:
  _target_: llm_synthesis.data_loader.paper_loader.hf_paper_loader.HFLoader
  dataset_uri: "LeMaterial/LeMat-Synth-Papers"
  dataset_config_name: "full"
  split: "chemrxiv"

number_of_samples: 1500
