architecture:
  _target_: llm_synthesis.data_loader.paper_loader.hf_paper_loader.HFLoader
  dataset_uri: "LeMaterial/LeMat-Synth"
  split: "train"
# architecture:
#   _target_: llm_synthesis.data_loader.paper_loader.fs_paper_loader.FSPaperLoader
#   data_dir: <local_path to data>
