architecture:
  _target_: llm_synthesis.data_loader.paper_loader.fs_paper_loader.FSPaperLoader
  # Folder for .txt files of parsed papers
  data_dir: "/Users/mlederbau/lematerial-llm-synthesis/annotations/wip/lemat-synth-arxiv"